import type { TDatasetAttribution, TFooterLinesParams, TFooterTextLine } from "@/types";

/** "WorldClim v2.1 (CRU-TS 4.09)" — both numbers fetched live from WorldClim's
 * Raster resource, not hardcoded. Cited together regardless of dataset: even
 * climate-mode exports are grounded in WorldClim's v2.1 baseline, and weather
 * rasters are that baseline downscaled with CRU-TS anomalies. */
export function formatDatasetAttribution(attribution: TDatasetAttribution | null): string {
  if (!attribution) return "WorldClim data";
  const { worldclim, cruTs } = attribution;
  return `${worldclim.creator} v${worldclim.version} (${cruTs.creator} ${cruTs.version}) data`;
}

/**
 * The share-URL line shrinks to fit on one line down to footerUrlMinFontSize.
 * If it still doesn't fit even at that size, it wraps across as many lines as
 * needed (all at the minimum size) instead of overflowing the canvas.
 */
function buildShareUrlLines(url: string, layout: TFooterLinesParams["layout"]): TFooterTextLine[] {
  const { width, paddingX, footerFontSize, footerUrlMinFontSize, footerUrlAvgCharWidthRatio } =
    layout;
  const availableWidth = width - paddingX * 2;
  const maxCharsAtSize = (fontSize: number) =>
    Math.max(1, Math.floor(availableWidth / (fontSize * footerUrlAvgCharWidthRatio)));

  const fittedSingleLineSize = Math.floor(
    availableWidth / (url.length * footerUrlAvgCharWidthRatio),
  );
  if (fittedSingleLineSize >= footerUrlMinFontSize) {
    return [{ text: url, fontSize: Math.min(footerFontSize, fittedSingleLineSize) }];
  }

  const charsPerLine = maxCharsAtSize(footerUrlMinFontSize);
  const lines: TFooterTextLine[] = [];
  for (let i = 0; i < url.length; i += charsPerLine) {
    lines.push({ text: url.slice(i, i + charsPerLine), fontSize: footerUrlMinFontSize });
  }
  return lines;
}

/** The footer every export image (PNG/SVG, any page) carries as a mandatory
 * block — brand/context, live WorldClim+CRU-TS attribution, and a shareable
 * link back to this exact view. Callers derive their canvas height from
 * `lines.length`, since the share-URL line can wrap to more than one line. */
export function buildFooterTextLines(params: TFooterLinesParams): TFooterTextLine[] {
  const { contextLabel, datasetAttribution, shareUrl, layout } = params;

  return [
    { text: `Climatica · WorldClim · ${contextLabel}`, fontSize: layout.footerFontSize },
    {
      text: `Generated by climatica.gsic.uva.es using ${formatDatasetAttribution(datasetAttribution)}`,
      fontSize: layout.footerFontSize,
    },
    ...buildShareUrlLines(shareUrl, layout),
  ];
}
