name: Deploy Climatica

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Update repository
        run: |
          export PATH=/home/guiveg/.nvm/versions/node/v25.1.0/bin:$PATH
          cd /home/guiveg/climatica-nextjs
          git fetch --all --tags
          git checkout ${GITHUB_REF_NAME}

      - name: Install dependencies
        run: |
          export PATH=/home/guiveg/.nvm/versions/node/v25.1.0/bin:$PATH
          cd /home/guiveg/climatica-nextjs
          npm ci

      - name: Build application
        run: |
          export PATH=/home/guiveg/.nvm/versions/node/v25.1.0/bin:$PATH
          cd /home/guiveg/climatica-nextjs
          npm run build

      - name: Restart service
        run: |
          sudo systemctl restart climatica

      - name: Verify service
        run: |
          sudo systemctl is-active climatica
